const Auth = require("../Models/Auth");
const connectDB = require("../config/db");
const bcrypt = require("bcryptjs");

const authRecords = [
  {
    _id: "AUTH1001",
    email: "rahul.sharma@example.com",
    password: "hashed_password_1",
    level: 1,
    linked_id: "USER1001",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1002",
    email: "aditi.verma@example.com",
    password: "hashed_password_2",
    level: 1,
    linked_id: "USER1002",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1003",
    email: "karthik.reddy@example.com",
    password: "hashed_password_3",
    level: 1,
    linked_id: "USER1003",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1004",
    email: "meera.iyer@example.com",
    password: "hashed_password_4",
    level: 1,
    linked_id: "USER1004",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1005",
    email: "rohan.desai@example.com",
    password: "hashed_password_5",
    level: 1,
    linked_id: "USER1005",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1006",
    email: "sanya.kapoor@example.com",
    password: "hashed_password_6",
    level: 1,
    linked_id: "USER1006",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1007",
    email: "vikram.joshi@example.com",
    password: "hashed_password_7",
    level: 1,
    linked_id: "USER1007",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1008",
    email: "neha.aggarwal@example.com",
    password: "hashed_password_8",
    level: 1,
    linked_id: "USER1008",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1009",
    email: "arjun.menon@example.com",
    password: "hashed_password_9",
    level: 1,
    linked_id: "USER1009",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1010",
    email: "pooja.bhatia@example.com",
    password: "hashed_password_10",
    level: 1,
    linked_id: "USER1010",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1011",
    email: "harsh.vardhan@example.com",
    password: "hashed_password_11",
    level: 1,
    linked_id: "USER1011",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1012",
    email: "ananya.patel@example.com",
    password: "hashed_password_12",
    level: 1,
    linked_id: "USER1012",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1013",
    email: "devraj.singh@example.com",
    password: "hashed_password_13",
    level: 1,
    linked_id: "USER1013",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1014",
    email: "rashmi.rao@example.com",
    password: "hashed_password_14",
    level: 1,
    linked_id: "USER1014",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1015",
    email: "sameer.khan@example.com",
    password: "hashed_password_15",
    level: 1,
    linked_id: "USER1015",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1016",
    email: "divya.nair@example.com",
    password: "hashed_password_16",
    level: 1,
    linked_id: "USER1016",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1017",
    email: "anil.gupta@example.com",
    password: "hashed_password_17",
    level: 1,
    linked_id: "USER1017",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1018",
    email: "ritika.das@example.com",
    password: "hashed_password_18",
    level: 1,
    linked_id: "USER1018",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1019",
    email: "arvind.pillai@example.com",
    password: "hashed_password_19",
    level: 1,
    linked_id: "USER1019",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1020",
    email: "sneha.chatterjee@example.com",
    password: "hashed_password_20",
    level: 1,
    linked_id: "USER1020",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1021",
    email: "manoj.kumar@example.com",
    password: "hashed_password_21",
    level: 1,
    linked_id: "USER1021",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1022",
    email: "swati.malhotra@example.com",
    password: "hashed_password_22",
    level: 1,
    linked_id: "USER1022",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1023",
    email: "rakesh.mehta@example.com",
    password: "hashed_password_23",
    level: 1,
    linked_id: "USER1023",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1024",
    email: "priya.sharma@example.com",
    password: "hashed_password_24",
    level: 1,
    linked_id: "USER1024",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1025",
    email: "aakash.sinha@example.com",
    password: "hashed_password_25",
    level: 1,
    linked_id: "USER1025",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1026",
    email: "deepika.banerjee@example.com",
    password: "hashed_password_26",
    level: 1,
    linked_id: "USER1026",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1027",
    email: "vishal.menon@example.com",
    password: "hashed_password_27",
    level: 1,
    linked_id: "USER1027",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1028",
    email: "pallavi.rao@example.com",
    password: "hashed_password_28",
    level: 1,
    linked_id: "USER1028",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1029",
    email: "nitin.kulkarni@example.com",
    password: "hashed_password_29",
    level: 1,
    linked_id: "USER1029",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1030",
    email: "anusha.reddy@example.com",
    password: "hashed_password_30",
    level: 1,
    linked_id: "USER1030",
    role: "User",
    last_login: new Date(),
    created_at: new Date(),
  },

  {
    _id: "AUTH1031",
    email: "rajesh.khanna@example.com",
    password: "hashed_password_31",
    level: 2,
    linked_id: "MED1001",
    role: "Mediator",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1032",
    email: "sangeeta.iyer@example.com",
    password: "hashed_password_32",
    level: 2,
    linked_id: "MED1002",
    role: "Mediator",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1033",
    email: "amit.trivedi@example.com",
    password: "hashed_password_33",
    level: 2,
    linked_id: "MED1003",
    role: "Mediator",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1034",
    email: "meenal.joshi@example.com",
    password: "hashed_password_34",
    level: 2,
    linked_id: "MED1004",
    role: "Mediator",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1035",
    email: "vikas.mehta@example.com",
    password: "hashed_password_35",
    level: 2,
    linked_id: "MED1005",
    role: "Mediator",
    last_login: new Date(),
    created_at: new Date(),
  },

  {
    _id: "AUTH1036",
    email: "anita.kapoor@example.com",
    password: "hashed_password_36",
    level: 2,
    linked_id: "MED1006",
    role: "Mediator",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1037",
    email: "raghav.bhatia@example.com",
    password: "hashed_password_37",
    level: 2,
    linked_id: "MED1007",
    role: "Mediator",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1038",
    email: "nisha.agarwal@example.com",
    password: "hashed_password_38",
    level: 2,
    linked_id: "MED1008",
    role: "Mediator",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1039",
    email: "rahul.deshmukh@example.com",
    password: "hashed_password_39",
    level: 2,
    linked_id: "MED1009",
    role: "Mediator",
    last_login: new Date(),
    created_at: new Date(),
  },
  {
    _id: "AUTH1040",
    email: "prakash.nair@example.com",
    password: "hashed_password_40",
    level: 2,
    linked_id: "MED1010",
    role: "Mediator",
    last_login: new Date(),
    created_at: new Date(),
  },

  {
    _id: "AUTH2001",
    email: "admin@nyaypath.com",
    password: "hashed_admin_password",
    level: 3,
    linked_id: null,
    role: "Admin",
    last_login: new Date(),
    created_at: new Date(),
  },
];

(async function () {
  connectDB();

  try {
    await Auth.deleteMany();
    console.log("Auth collection flushed!!!");

    const salt = await bcrypt.genSalt(10);
    const hashedAuthRecord = await Promise.all(
      authRecords.map(async (doc) => ({
        ...doc,
        password: await bcrypt.hash(doc.password, salt),
      }))
    );

    await Auth.insertMany(hashedAuthRecord);
    console.log("Auth collection seeded!!!");
    process.exit();
  } catch (err) {
    console.log("Error flushing or seeding Auth data", err);
    process.exit(1);
  }
})();
