const Case = require("../Models/Case");
const connectDB = require("../config/db");

const cases = [
  {
    _id: "CASE1001",
    case_type: "Family Dispute",
    language: "Hindi",
    parties: ["USER1001", "USER1002"],
    initiated_by: "USER1001",
    location: "Delhi",
    mediation_mode: "Online",
    assigned_mediator: "MED1001",
    status: "Mediator Assigned",
    result: null,
    documents: [
      {
        url: "https://example.com/documents/case1001.pdf",
        type: "PDF",
        uploaded_at: new Date(),
      },
    ],
    rate: 5000,
    priority: "Normal",
    creation_date: new Date(),
    last_updated: new Date(),
  },
  {
    _id: "CASE1002",
    case_type: "Property Dispute",
    language: "English",
    parties: ["USER1003", "USER1004"],
    initiated_by: "USER1003",
    location: "Mumbai",
    mediation_mode: "Offline",
    assigned_mediator: "MED1002",
    status: "In Progress",
    result: null,
    documents: [
      {
        url: "https://example.com/documents/case1002.pdf",
        type: "PDF",
        uploaded_at: new Date(),
      },
    ],
    rate: 7000,
    priority: "Urgent",
    creation_date: new Date(),
    last_updated: new Date(),
  },
  {
    _id: "CASE1003",
    case_type: "Business Dispute",
    language: "Gujarati",
    parties: ["USER1005", "USER1006"],
    initiated_by: "USER1005",
    location: "Ahmedabad",
    mediation_mode: "Offline",
    assigned_mediator: "MED1003",
    status: "Filed",
    result: null,
    documents: [
      {
        url: "https://example.com/documents/case1003.pdf",
        type: "PDF",
        uploaded_at: new Date(),
      },
    ],
    rate: 6000,
    priority: "Normal",
    creation_date: new Date(),
    last_updated: new Date(),
  },
  {
    _id: "CASE1004",
    case_type: "Employment Dispute",
    language: "Marathi",
    parties: ["USER1007", "USER1008"],
    initiated_by: "USER1007",
    location: "Pune",
    mediation_mode: "Online",
    assigned_mediator: "MED1004",
    status: "Closed",
    result: "Success",
    documents: [
      {
        url: "https://example.com/documents/case1004.pdf",
        type: "PDF",
        uploaded_at: new Date(),
      },
    ],
    rate: 4500,
    priority: "Normal",
    creation_date: new Date(),
    last_updated: new Date(),
  },
  {
    _id: "CASE1005",
    case_type: "Real Estate Dispute",
    language: "Tamil",
    parties: ["USER1009", "USER1010"],
    initiated_by: "USER1009",
    location: "Chennai",
    mediation_mode: "Offline",
    assigned_mediator: "MED1005",
    status: "Mediator Assigned",
    result: null,
    documents: [
      {
        url: "https://example.com/documents/case1005.pdf",
        type: "PDF",
        uploaded_at: new Date(),
      },
    ],
    rate: 5500,
    priority: "Urgent",
    creation_date: new Date(),
    last_updated: new Date(),
  },
  {
    _id: "CASE1006",
    case_type: "Consumer Dispute",
    language: "Telugu",
    parties: ["USER1011", "USER1012"],
    initiated_by: "USER1011",
    location: "Hyderabad",
    mediation_mode: "Online",
    assigned_mediator: "MED1006",
    status: "Filed",
    result: null,
    documents: [
      {
        url: "https://example.com/documents/case1006.pdf",
        type: "PDF",
        uploaded_at: new Date(),
      },
    ],
    rate: 4000,
    priority: "Normal",
    creation_date: new Date(),
    last_updated: new Date(),
  },
  {
    _id: "CASE1007",
    case_type: "Divorce Settlement",
    language: "Kannada",
    parties: ["USER1013", "USER1014"],
    initiated_by: "USER1013",
    location: "Bangalore",
    mediation_mode: "Offline",
    assigned_mediator: "MED1007",
    status: "In Progress",
    result: null,
    documents: [
      {
        url: "https://example.com/documents/case1007.pdf",
        type: "PDF",
        uploaded_at: new Date(),
      },
    ],
    rate: 6500,
    priority: "Urgent",
    creation_date: new Date(),
    last_updated: new Date(),
  },
  {
    _id: "CASE1008",
    case_type: "Bank Loan Dispute",
    language: "English",
    parties: ["USER1015", "USER1016"],
    initiated_by: "USER1015",
    location: "Chandigarh",
    mediation_mode: "Offline",
    assigned_mediator: "MED1008",
    status: "Closed",
    result: "Failed",
    documents: [
      {
        url: "https://example.com/documents/case1008.pdf",
        type: "PDF",
        uploaded_at: new Date(),
      },
    ],
    rate: 5800,
    priority: "Normal",
    creation_date: new Date(),
    last_updated: new Date(),
  },
  {
    _id: "CASE1009",
    case_type: "Intellectual Property Dispute",
    language: "Bengali",
    parties: ["USER1017", "USER1018"],
    initiated_by: "USER1017",
    location: "Kolkata",
    mediation_mode: "Online",
    assigned_mediator: "MED1009",
    status: "Mediator Assigned",
    result: null,
    documents: [
      {
        url: "https://example.com/documents/case1009.pdf",
        type: "PDF",
        uploaded_at: new Date(),
      },
    ],
    rate: 6200,
    priority: "Normal",
    creation_date: new Date(),
    last_updated: new Date(),
  },
  {
    _id: "CASE1010",
    case_type: "Land Dispute",
    language: "Marathi",
    parties: ["USER1019", "USER1020"],
    initiated_by: "USER1019",
    location: "Nagpur",
    mediation_mode: "Offline",
    assigned_mediator: "MED1010",
    status: "Filed",
    result: null,
    documents: [
      {
        url: "https://example.com/documents/case1010.pdf",
        type: "PDF",
        uploaded_at: new Date(),
      },
    ],
    rate: 7000,
    priority: "Urgent",
    creation_date: new Date(),
    last_updated: new Date(),
  },
  {
    _id: "CASE1011",
    case_type: "Workplace Harassment",
    language: "Hindi",
    parties: ["USER1021", "USER1022"],
    initiated_by: "USER1021",
    location: "Indore",
    mediation_mode: "Online",
    assigned_mediator: "MED1003",
    status: "Closed",
    result: "Success",
    documents: [
      {
        url: "https://example.com/documents/case1011.pdf",
        type: "PDF",
        uploaded_at: new Date(),
      },
    ],
    rate: 5500,
    priority: "Normal",
    creation_date: new Date(),
    last_updated: new Date(),
  },
  {
    _id: "CASE1012",
    case_type: "Cyber Crime Dispute",
    language: "English",
    parties: ["USER1023", "USER1024"],
    initiated_by: "USER1023",
    location: "Bhopal",
    mediation_mode: "Online",
    assigned_mediator: "MED1004",
    status: "In Progress",
    result: null,
    documents: [
      {
        url: "https://example.com/documents/case1012.pdf",
        type: "PDF",
        uploaded_at: new Date(),
      },
    ],
    rate: 6200,
    priority: "Urgent",
    creation_date: new Date(),
    last_updated: new Date(),
  },
  {
    _id: "CASE1013",
    case_type: "Insurance Claim Dispute",
    language: "Tamil",
    parties: ["USER1025", "USER1026"],
    initiated_by: "USER1025",
    location: "Madurai",
    mediation_mode: "Offline",
    assigned_mediator: "MED1005",
    status: "Mediator Assigned",
    result: null,
    documents: [
      {
        url: "https://example.com/documents/case1013.pdf",
        type: "PDF",
        uploaded_at: new Date(),
      },
    ],
    rate: 5800,
    priority: "Normal",
    creation_date: new Date(),
    last_updated: new Date(),
  },
  {
    _id: "CASE1014",
    case_type: "Medical Negligence",
    language: "Telugu",
    parties: ["USER1027", "USER1028"],
    initiated_by: "USER1027",
    location: "Vijayawada",
    mediation_mode: "Online",
    assigned_mediator: "MED1006",
    status: "Closed",
    result: "Success",
    documents: [
      {
        url: "https://example.com/documents/case1014.pdf",
        type: "PDF",
        uploaded_at: new Date(),
      },
    ],
    rate: 7000,
    priority: "Urgent",
    creation_date: new Date(),
    last_updated: new Date(),
  },
  {
    _id: "CASE1015",
    case_type: "Environmental Dispute",
    language: "Kannada",
    parties: ["USER1029", "USER1030"],
    initiated_by: "USER1029",
    location: "Mysore",
    mediation_mode: "Online",
    assigned_mediator: "MED1007",
    status: "Filed",
    result: null,
    documents: [
      {
        url: "https://example.com/documents/case1015.pdf",
        type: "PDF",
        uploaded_at: new Date(),
      },
    ],
    rate: 5000,
    priority: "Normal",
    creation_date: new Date(),
    last_updated: new Date(),
  },
];

(async function () {
  connectDB();

  try {
    await Case.deleteMany();
    console.log("Cases collection flushed!!!");

    await Case.insertMany(cases);
    console.log("Cases collection seeded!!!");
    process.exit();
  } catch (err) {
    console.log("Error flushing or seeding Cases data", err);
    process.exit(1);
  }
})();
