const Mediator = require("../Models/Mediator");
const connectDB = require("../config/db");

const mediators = [
  {
    _id: "MED1001",
    full_name: "Rajesh Khanna",
    DOB: "1980-05-15",
    gender: "Male",
    number: "+918765432201",
    email: "rajesh.khanna@example.com",
    address: { city: "Delhi", state: "Delhi", country: "India" },
    languages_spoken: ["Hindi", "English"],
    specializations: ["Family Disputes", "Property Disputes"],
    mediation_type: ["Pre-Litigation", "Court-Referred"],
    education_qualification: ["LLB", "Mediation Training Certification"],
    years_of_experience: 12,
    profile_pic: "https://example.com/profiles/rajesh.jpg",
    cases: ["CASE1001"],
    price: 5000,
    status: "Available",
    mode: "Online",
    level: "Advanced",
    verification_status: "Verified",
  },
  {
    _id: "MED1002",
    full_name: "Sangeeta Iyer",
    DOB: "1978-11-20",
    gender: "Female",
    number: "+918765432202",
    email: "sangeeta.iyer@example.com",
    address: { city: "Mumbai", state: "Maharashtra", country: "India" },
    languages_spoken: ["English", "Marathi"],
    specializations: ["Commercial Disputes", "Employment Disputes"],
    mediation_type: ["Community Mediation"],
    education_qualification: ["LLM", "Certified Mediator"],
    years_of_experience: 15,
    profile_pic: "https://example.com/profiles/sangeeta.jpg",
    cases: ["CASE1002"],
    price: 7000,
    status: "Busy",
    mode: "Hybrid",
    level: "Advanced",
    verification_status: "Verified",
  },
  {
    _id: "MED1003",
    full_name: "Amit Trivedi",
    DOB: "1985-09-10",
    gender: "Male",
    number: "+918765432203",
    email: "amit.trivedi@example.com",
    address: { city: "Ahmedabad", state: "Gujarat", country: "India" },
    languages_spoken: ["Gujarati", "Hindi", "English"],
    specializations: ["Business Disputes", "Banking Disputes"],
    mediation_type: ["Court-Referred"],
    education_qualification: ["LLB", "Diploma in ADR"],
    years_of_experience: 10,
    profile_pic: "https://example.com/profiles/amit.jpg",
    cases: ["CASE1003", "CASE1011"],
    price: 6000,
    status: "Available",
    mode: "Offline",
    level: "Intermediate",
    verification_status: "Pending",
  },
  {
    _id: "MED1004",
    full_name: "Meenal Joshi",
    DOB: "1990-07-25",
    gender: "Female",
    number: "+918765432204",
    email: "meenal.joshi@example.com",
    address: { city: "Pune", state: "Maharashtra", country: "India" },
    languages_spoken: ["Marathi", "English"],
    specializations: ["Workplace Conflicts", "Divorce Settlements"],
    mediation_type: ["Private Mediation"],
    education_qualification: ["Psychology Degree", "Certified Mediator"],
    years_of_experience: 8,
    profile_pic: "https://example.com/profiles/meenal.jpg",
    cases: ["CASE1004", "CASE1012"],
    price: 4500,
    status: "Available",
    mode: "Online",
    level: "Basic",
    verification_status: "Verified",
  },
  {
    _id: "MED1005",
    full_name: "Vikas Mehta",
    DOB: "1982-06-15",
    gender: "Male",
    number: "+918765432205",
    email: "vikas.mehta@example.com",
    address: { city: "Jaipur", state: "Rajasthan", country: "India" },
    languages_spoken: ["Hindi", "English"],
    specializations: ["Property Disputes", "Contractual Disputes"],
    mediation_type: ["Community Mediation"],
    education_qualification: ["LLB", "ADR Certification"],
    years_of_experience: 14,
    profile_pic: "https://example.com/profiles/vikas.jpg",
    cases: ["CASE1005", "CASE1013"],
    price: 5500,
    status: "Busy",
    mode: "Hybrid",
    level: "Intermediate",
    verification_status: "Verified",
  },
  {
    _id: "MED1006",
    full_name: "Anita Kapoor",
    DOB: "1975-08-30",
    gender: "Female",
    number: "+918765432206",
    email: "anita.kapoor@example.com",
    address: { city: "Chennai", state: "Tamil Nadu", country: "India" },
    languages_spoken: ["Tamil", "English"],
    specializations: ["Family Disputes", "Child Custody"],
    mediation_type: ["Pre-Litigation"],
    education_qualification: ["LLM", "Certified Family Mediator"],
    years_of_experience: 18,
    profile_pic: "https://example.com/profiles/anita.jpg",
    cases: ["CASE1006", "CASE1014"],
    price: 7500,
    status: "Available",
    mode: "Offline",
    level: "Advanced",
    verification_status: "Verified",
  },
  {
    _id: "MED1007",
    full_name: "Raghav Bhatia",
    DOB: "1987-12-10",
    gender: "Male",
    number: "+918765432207",
    email: "raghav.bhatia@example.com",
    address: { city: "Lucknow", state: "Uttar Pradesh", country: "India" },
    languages_spoken: ["Hindi", "English"],
    specializations: ["Criminal Mediation", "Employment Disputes"],
    mediation_type: ["Court-Referred"],
    education_qualification: ["LLB", "Criminal Mediation Training"],
    years_of_experience: 9,
    profile_pic: "https://example.com/profiles/raghav.jpg",
    cases: ["CASE1007", "CASE1015"],
    price: 6500,
    status: "Available",
    mode: "Hybrid",
    level: "Intermediate",
    verification_status: "Verified",
  },
  {
    _id: "MED1008",
    full_name: "Nisha Agarwal",
    DOB: "1983-03-18",
    gender: "Female",
    number: "+918765432209",
    email: "nisha.agarwal@example.com",
    address: { city: "Kolkata", state: "West Bengal", country: "India" },
    languages_spoken: ["Bengali", "English", "Hindi"],
    specializations: ["Intellectual Property Disputes", "Consumer Disputes"],
    mediation_type: ["Pre-Litigation", "Community Mediation"],
    education_qualification: ["LLM", "Certified IP Mediator"],
    years_of_experience: 14,
    profile_pic: "https://example.com/profiles/nisha.jpg",
    cases: ["CASE1008"],
    price: 6200,
    status: "Available",
    mode: "Hybrid",
    level: "Advanced",
    verification_status: "Verified",
  },
  {
    _id: "MED1009",
    full_name: "Rahul Deshmukh",
    DOB: "1981-07-22",
    gender: "Male",
    number: "+918765432210",
    email: "rahul.deshmukh@example.com",
    address: { city: "Nagpur", state: "Maharashtra", country: "India" },
    languages_spoken: ["Marathi", "English", "Hindi"],
    specializations: ["Land Disputes", "Real Estate Disputes"],
    mediation_type: ["Court-Referred", "Private Mediation"],
    education_qualification: ["LLB", "Certified Real Estate Mediator"],
    years_of_experience: 16,
    profile_pic: "https://example.com/profiles/rahul.jpg",
    cases: ["CASE1009"],
    price: 7000,
    status: "Busy",
    mode: "Offline",
    level: "Advanced",
    verification_status: "Verified",
  },
  {
    _id: "MED1010",
    full_name: "Prakash Nair",
    DOB: "1984-04-10",
    gender: "Male",
    number: "+918765432210",
    email: "prakash.nair@example.com",
    address: { city: "Thiruvananthapuram", state: "Kerala", country: "India" },
    languages_spoken: ["Malayalam", "English"],
    specializations: ["Environmental Disputes", "Community Conflicts"],
    mediation_type: ["Community Mediation", "Pre-Litigation"],
    education_qualification: ["LLM", "Certified Environmental Mediator"],
    years_of_experience: 14,
    profile_pic: "https://example.com/profiles/prakash.jpg",
    cases: ["CASE1015"],
    price: 5400,
    status: "Available",
    mode: "Hybrid",
    level: "Advanced",
    verification_status: "Verified",
  },
];

(async function () {
  connectDB();

  try {
    await Mediator.deleteMany();
    console.log("Mediator collection flushed!!!");
    await Mediator.insertMany(mediators);
    console.log("Mediator collection seeded!!!");
    process.exit();
  } catch (err) {
    console.log("Error flushing or seeding Mediator data", err);
    process.exit(1);
  }
})();
