const User = require("../Models/User");
const connectDB = require("../config/db");

const users = [
  {
    _id: "USER1001",
    full_name: "Rahul Sharma",
    number: "+918765432101",
    email: "rahul.sharma@example.com",
    address: { city: "Delhi", state: "Delhi", country: "India" },
    language_preference: "Hindi",
    user_type: "LegalAid",
    cases_involved: ["CASE1001"],
  },
  {
    _id: "USER1002",
    full_name: "Aditi Verma",
    number: "+918765432102",
    email: "aditi.verma@example.com",
    address: { city: "Mumbai", state: "Maharashtra", country: "India" },
    language_preference: "English",
    user_type: "Citizen",
    cases_involved: ["CASE1001"],
  },
  {
    _id: "USER1003",
    full_name: "Karthik Reddy",
    number: "+918765432103",
    email: "karthik.reddy@example.com",
    address: { city: "Hyderabad", state: "Telangana", country: "India" },
    language_preference: "Telugu",
    user_type: "NGO",
    cases_involved: ["CASE1002"],
  },
  {
    _id: "USER1004",
    full_name: "Meera Iyer",
    number: "+918765432104",
    email: "meera.iyer@example.com",
    address: { city: "Chennai", state: "Tamil Nadu", country: "India" },
    language_preference: "Tamil",
    user_type: "Court",
    cases_involved: ["CASE1002"],
  },
  {
    _id: "USER1005",
    full_name: "Rohan Desai",
    number: "+918765432105",
    email: "rohan.desai@example.com",
    address: { city: "Ahmedabad", state: "Gujarat", country: "India" },
    language_preference: "Gujarati",
    user_type: "Court",
    cases_involved: ["CASE1003"],
  },
  {
    _id: "USER1006",
    full_name: "Sanya Kapoor",
    number: "+918765432106",
    email: "sanya.kapoor@example.com",
    address: { city: "Kolkata", state: "West Bengal", country: "India" },
    language_preference: "Bengali",
    user_type: "LegalAid",
    cases_involved: ["CASE1003"],
  },
  {
    _id: "USER1007",
    full_name: "Vikram Joshi",
    number: "+918765432107",
    email: "vikram.joshi@example.com",
    address: { city: "Pune", state: "Maharashtra", country: "India" },
    language_preference: "Marathi",
    user_type: "NGO",
    cases_involved: ["CASE1004"],
  },
  {
    _id: "USER1008",
    full_name: "Neha Aggarwal",
    number: "+918765432108",
    email: "neha.aggarwal@example.com",
    address: { city: "Jaipur", state: "Rajasthan", country: "India" },
    language_preference: "Hindi",
    user_type: "Citizen",
    cases_involved: ["CASE1004"],
  },
  {
    _id: "USER1009",
    full_name: "Arjun Menon",
    number: "+918765432109",
    email: "arjun.menon@example.com",
    address: { city: "Bangalore", state: "Karnataka", country: "India" },
    language_preference: "Kannada",
    user_type: "LegalAid",
    cases_involved: ["CASE1005"],
  },
  {
    _id: "USER1010",
    full_name: "Pooja Bhatia",
    number: "+918765432110",
    email: "pooja.bhatia@example.com",
    address: { city: "Lucknow", state: "Uttar Pradesh", country: "India" },
    language_preference: "Hindi",
    user_type: "Court",
    cases_involved: ["CASE1005"],
  },
  {
    _id: "USER1011",
    full_name: "Harsh Vardhan",
    number: "+918765432111",
    email: "harsh.vardhan@example.com",
    address: { city: "Bhopal", state: "Madhya Pradesh", country: "India" },
    language_preference: "Hindi",
    user_type: "NGO",
    cases_involved: ["CASE1006"],
  },
  {
    _id: "USER1012",
    full_name: "Ananya Patel",
    number: "+918765432112",
    email: "ananya.patel@example.com",
    address: { city: "Surat", state: "Gujarat", country: "India" },
    language_preference: "Gujarati",
    user_type: "NGO",
    cases_involved: ["CASE1006"],
  },
  {
    _id: "USER1013",
    full_name: "Devraj Singh",
    number: "+918765432113",
    email: "devraj.singh@example.com",
    address: { city: "Chandigarh", state: "Chandigarh", country: "India" },
    language_preference: "Punjabi",
    user_type: "LegalAid",
    cases_involved: ["CASE1007"],
  },
  {
    _id: "USER1014",
    full_name: "Rashmi Rao",
    number: "+918765432114",
    email: "rashmi.rao@example.com",
    address: { city: "Mysore", state: "Karnataka", country: "India" },
    language_preference: "Kannada",
    user_type: "NGO",
    cases_involved: ["CASE1007"],
  },
  {
    _id: "USER1015",
    full_name: "Sameer Khan",
    number: "+918765432115",
    email: "sameer.khan@example.com",
    address: { city: "Nagpur", state: "Maharashtra", country: "India" },
    language_preference: "Urdu",
    user_type: "Citizen",
    cases_involved: ["CASE1008"],
  },
  {
    _id: "USER1016",
    full_name: "Divya Nair",
    number: "+918765432116",
    email: "divya.nair@example.com",
    address: { city: "Thiruvananthapuram", state: "Kerala", country: "India" },
    language_preference: "Malayalam",
    user_type: "Other",
    cases_involved: ["CASE1008"],
  },
  {
    _id: "USER1017",
    full_name: "Anil Gupta",
    number: "+918765432117",
    email: "anil.gupta@example.com",
    address: { city: "Varanasi", state: "Uttar Pradesh", country: "India" },
    language_preference: "Hindi",
    user_type: "Other",
    cases_involved: ["CASE1009"],
  },
  {
    _id: "USER1018",
    full_name: "Ritika Das",
    number: "+918765432118",
    email: "ritika.das@example.com",
    address: { city: "Guwahati", state: "Assam", country: "India" },
    language_preference: "Assamese",
    user_type: "Court",
    cases_involved: ["CASE1009"],
  },
  {
    _id: "USER1019",
    full_name: "Arvind Pillai",
    number: "+918765432119",
    email: "arvind.pillai@example.com",
    address: { city: "Coimbatore", state: "Tamil Nadu", country: "India" },
    language_preference: "Tamil",
    user_type: "Citizen",
    cases_involved: ["CASE1010"],
  },
  {
    _id: "USER1020",
    full_name: "Sneha Chatterjee",
    number: "+918765432120",
    email: "sneha.chatterjee@example.com",
    address: { city: "Howrah", state: "West Bengal", country: "India" },
    language_preference: "Bengali",
    user_type: "Other",
    cases_involved: ["CASE1010"],
  },
  {
    _id: "USER1021",
    full_name: "Manoj Kumar",
    number: "+918765432121",
    email: "manoj.kumar@example.com",
    address: { city: "Patna", state: "Bihar", country: "India" },
    language_preference: "Hindi",
    user_type: "Other",
    cases_involved: ["CASE1011"],
  },
  {
    _id: "USER1022",
    full_name: "Swati Malhotra",
    number: "+918765432122",
    email: "swati.malhotra@example.com",
    address: { city: "Indore", state: "Madhya Pradesh", country: "India" },
    language_preference: "Hindi",
    user_type: "Court",
    cases_involved: ["CASE1011"],
  },
  {
    _id: "USER1023",
    full_name: "Rakesh Mehta",
    number: "+918765432123",
    email: "rakesh.mehta@example.com",
    address: { city: "Bhopal", state: "Madhya Pradesh", country: "India" },
    language_preference: "English",
    user_type: "LegalAid",
    cases_involved: ["CASE1012"],
  },
  {
    _id: "USER1024",
    full_name: "Priya Sharma",
    number: "+918765432124",
    email: "priya.sharma@example.com",
    address: { city: "Gandhinagar", state: "Gujarat", country: "India" },
    language_preference: "Gujarati",
    user_type: "Police",
    cases_involved: ["CASE1012"],
  },
  {
    _id: "USER1025",
    full_name: "Aakash Sinha",
    number: "+918765432125",
    email: "aakash.sinha@example.com",
    address: { city: "Madurai", state: "Tamil Nadu", country: "India" },
    language_preference: "Tamil",
    user_type: "Citizen",
    cases_involved: ["CASE1013"],
  },
  {
    _id: "USER1026",
    full_name: "Deepika Banerjee",
    number: "+918765432126",
    email: "deepika.banerjee@example.com",
    address: { city: "Kolkata", state: "West Bengal", country: "India" },
    language_preference: "Bengali",
    user_type: "Police",
    cases_involved: ["CASE1013"],
  },
  {
    _id: "USER1027",
    full_name: "Vishal Menon",
    number: "+918765432127",
    email: "vishal.menon@example.com",
    address: { city: "Vijayawada", state: "Andhra Pradesh", country: "India" },
    language_preference: "Telugu",
    user_type: "Police",
    cases_involved: ["CASE1014"],
  },
  {
    _id: "USER1028",
    full_name: "Pallavi Rao",
    number: "+918765432128",
    email: "pallavi.rao@example.com",
    address: {
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      country: "India",
    },
    language_preference: "Telugu",
    user_type: "Police",
    cases_involved: ["CASE1014"],
  },
  {
    _id: "USER1029",
    full_name: "Nitin Kulkarni",
    number: "+918765432129",
    email: "nitin.kulkarni@example.com",
    address: { city: "Mysore", state: "Karnataka", country: "India" },
    language_preference: "Kannada",
    user_type: "Citizen",
    cases_involved: ["CASE1015"],
  },
  {
    _id: "USER1030",
    full_name: "Anusha Reddy",
    number: "+918765432130",
    email: "anusha.reddy@example.com",
    address: { city: "Bangalore", state: "Karnataka", country: "India" },
    language_preference: "Kannada",
    user_type: "Police",
    cases_involved: ["CASE1015"],
  },
];

(async function () {
  connectDB();
  try {
    await User.deleteMany();
    console.log("User collection flushed!!!");

    await User.insertMany(users);
    console.log("User data seeded!!!");
    process.exit();
  } catch (err) {
    console.log("Error flushing or seeding User data", err);
    process.exit(1);
  }
})();
