const dotenv = require("dotenv");
dotenv.config();

const ENV = {
  SERV_PORT: process.env.SERV_PORT,
  DB_URL: process.env.MONGODB_URL,
  JWT_SECRET: process.env.JWT_SECRET,
  NODE_ENV: process.env.NODE_ENV,
  AZURE_OPENAI_ENDPOINT: process.env.AZURE_OPENAI_ENDPOINT,
  AZURE_OPENAI_KEY: process.env.AZURE_OPENAI_KEY,
  AZURE_DEPLOYMENT_NAME: process.env.AZURE_DEPLOYMENT_NAME,
  AZURE_API_VERSION: process.env.AZURE_API_VERSION,
  BHASHINI_SERVICE_ID: process.env.BHASHINI_SERVICE_ID,
  BHASHINI_API_KEY: process.env.BHASHINI_API_KEY,
  BHASHINI_AUTHORIZATION: process.env.BHASHINI_AUTHORIZATION,
  INFURA_HTTP: process.env.INFURA_HTTP,
  INFURA_PROJECT_ID: process.env.INFURA_PROJECT_ID,
  INFURA_PROJECT_SECRET: process.env.INFURA_PROJECT_SECRET,
  PINATA_JWT_TOKEN: process.env.PINATA_JWT_TOKEN,
};

module.exports = ENV;
